;; This file is automatically generated by the multiple-cursors
;; extension.
;; It keeps track of your preferences for running commands with
;; multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        paredit-kill
        paredit-open-round
        paredit-semicolon
        paredit-splice-sexp-killing-backward
        smex
        wdired-finish-edit
        ))

(setq mc/cmds-to-run-once
      '(
        dired-find-alternate-file
        ))
